categories: 分類
search: 搜索
tags: 標籤
tagcloud: 標籤雲
tweets: 推文
prev: 上一頁
next: 下一頁
comment: 留言
archive_a: 歸檔
archive_b: 歸檔：%s
page: 第 %d 頁
recent_posts: 最新文章
close: 關閉
posts_list: 文章目錄
location:
  about: 關於
  blog: 文章
  categories: 分類
  links: 友站
  projects: 項目
  search: 搜索
  tags: 標籤
